server:
  addr: ":8080"
  tcp_enable: true
  tcp_addr: ":8081"
  log_level: "debug"

ip_header:
  trusted_real_ip_header: "X-Internal-Real-IP"

security:
  access_token: "my-secret-token"
  rate_duration: "5s"
  enable_ua_block: true
  blocked_user_agents:
    - "nmap"
    - "scan"
    - "zgrab"
    - "spider"